<script lang="ts">
	// --- Components ---
	import { Flex, Span } from '@ui';

	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { MenuProps } from '..';
	import { getCtx } from '../ctx';
	import { onMount } from 'svelte';
	import { fade } from 'svelte/transition';
	import { cubicInOut } from 'svelte/easing';
	import { directives } from '@root/lib/internal/directives';

	let {
		children,
		class: className,
        backdropClass = $bindable('fixed left-0 top-0 size-full bg-black/40 backdrop-blur-xl'),
		menuClass = $bindable('flex flex-col w-[300px] h-full bg-black/20 '),

        classBackdrop,
		...rest
	}: MenuProps = $props();

	// Setup Menu's class
    let backdropCls = $state(cn(backdropClass, classBackdrop))
	let menuCls = $state(cn(menuClass, className));
	$effect(() => {
        backdropCls = cn(backdropClass, classBackdrop)
		menuCls = cn(menuClass, className);
	});

	// Get Drawer Context
	const { show$ } = getCtx();
	$effect(() => {
		console.log($show$);
	});

    function slide(node: HTMLElement, params: {duration?: number} = {}) {
        const existingTransform = getComputedStyle(node).transform.replace('none', '');
     
        return {
            duration: params.duration || 300,
            easing: cubicInOut,
            css: (t: number) => `transform: ${existingTransform} translateX(${(1-t) * -300}px;`
        }
    }

    function closeDrawer() {
        show$.set(false)
    }
</script>

<!-- Actual Menu -->
<div use:directives class={menuCls} onoutclick={() => closeDrawer()}>
	<Flex.Col class="w-full py-4 items-center box-border">
		<Span class="text-2xl">This is a drawer</Span>
	</Flex.Col>
	{@render children?.()}
	<Flex.Row>
		
	</Flex.Row>
</div>
<!--@component
    Generated by SvelteForge🔥
-->
