<script lang="ts">
	// --- Components ---
	import { Flex } from '@ui';

	// --- Logic ---
	import { base } from '$app/paths';
	import { cn } from '@lib/utils';
	import type { ItemProps } from '..';
	import { getCtx, getDrawerDropdownCtx } from '../ctx';
	import { fade } from 'svelte/transition';

	let {
		// Children >)]|
		children,

		// Component Props
		href = undefined,
		root = undefined,

		// Classes
		class: className,
		itemClass = $bindable(
			'animate box-border px-2 box-border py-2 gap-3 items-center w-10 hover:bg-black/20 select-none rounded-md cursor-pointer text-white dark:text-white'
		),

		// Component Slots
		slot_text,
		slot_right,

		...rest
	}: ItemProps = $props();

	// Setup Item's class
	let itemCls = $state(cn(itemClass, className));
	$effect(() => {
		itemCls = cn(itemClass, className);
	});

	href = base + href;

	// Get Drawer Context
	const { show$ } = getCtx();
	const dropdownCtx = getDrawerDropdownCtx();

	function onclick(event: MouseEvent) {
		if (!dropdownCtx) return;
		const dropdown_show$ = dropdownCtx['dropdown_show$']; // Scuffed
		dropdown_show$.update((current_show) => {
			return !current_show; // Flip Value
		});
	}
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<svelte:element this={href !== 'undefined' ? 'a' : 'div'} {href} {onclick}>
	<Flex.Row
		class={cn(
			itemCls,
			$show$ && 'px-6 w-full',
			dropdownCtx && !(root == true) && 'w-[80%] ml-auto'
		)}
		{...rest}
	>
		{@render children?.()}
		{#if $show$}
			<div transition:fade>
				{@render slot_text?.()}
			</div>
		{/if}

		{@render slot_right?.(dropdownCtx)}
	</Flex.Row>
</svelte:element>
<!--@component
    Generated by SvelteForge🔥
-->
