<script lang="ts">
	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { DropdownProps } from '..';
	import { setDrawerDropdownCtx } from '../ctx';

	let {
		children,
		class: className,
		dropdownClass = $bindable(''),

		// Extra Props Here
		disabled = false
	}: DropdownProps = $props();

	// Setup Dropdown's class
	let dropdownCls = $state(cn(dropdownClass, className));
	$effect(() => {
		dropdownCls = cn(dropdownClass, className);
	});

	const { disabled$ } = setDrawerDropdownCtx({ disabled });

	function onclick(event: MouseEvent) {
		if ($disabled$) return;
		// Do default activities
        console.debug(`[onclick:drawer-dropdown] ${event}`)
	}
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<!-- svelte-ignore a11y_click_events_have_key_events -->
<div class={cn(dropdownCls, $disabled$ && 'cursor-none opacity-50')} {onclick}>
	{@render children?.()}
</div>

<!--@component
    Generated by SvelteForge🔥
-->
