<script lang="ts">
	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { DropdownProps } from '..';
	import { setDrawerDropdownCtx } from '../ctx';
	import { Flex } from '@ui';
	import { fade } from 'svelte/transition';
	import { cubicOut } from 'svelte/easing';

	let {
		children,
		class: className,
		dropdownClass = $bindable(''),

		// Extra Props Here
		disabled = false,

		// Snippets
		slot_root
	}: DropdownProps = $props();

	// Setup Dropdown's class
	let dropdownCls = $state(cn(dropdownClass, className));
	$effect(() => {
		dropdownCls = cn(dropdownClass, className);
	});

	const { disabled$, dropdown_show$ } = setDrawerDropdownCtx({ disabled });

	function onclick(event: MouseEvent) {
		if ($disabled$) return;
		// Do default activities
		console.debug(`[onclick:drawer-dropdown] ${event}`);
	}

	function expand(node: HTMLElement, params: any, { duration = 300 }) {
		const height = node.scrollHeight;

		return {
			duration,
			easing: params.easing || cubicOut,
			css: (t: number) => `height: ${t * height}px; opacity: ${t}; margin-top: ${t * 8}px;`,
		};
	}
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<!-- svelte-ignore a11y_click_events_have_key_events -->
<div class={cn(dropdownCls, $disabled$ && 'cursor-none opacity-50')} {onclick}>
	{@render slot_root?.($dropdown_show$)}

	{#if $dropdown_show$}
		<div class="flex flex-col relative ease-out gap-2 box-border mt-2" transition:expand >
			{@render children?.()}
		</div>
	{/if}
</div>

<!--@component
    Generated by SvelteForge🔥
-->
