<script lang="ts">

	// --- Styling ---
	import "./drawer.css"
	
	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { Props } from '..';
	import { setCtx } from '../ctx';

	let {
		children,
		class: className,
		drawerClass = $bindable(''),
	}: Props = $props();

	// Setup Drawer's class
	let drawerCls = $state(cn(drawerClass, className));
	$effect(() => {
		drawerCls = cn(drawerClass, className );
	});

	// Save drawer context
	setCtx({});
</script>



<div class={drawerCls}>
	{@render children?.()}
</div>

<!--@component
    Generated by SvelteForge🔥
-->
