<script lang="ts">
	// --- Components ---
	import { Flex, Separator } from '@ui';
	import IconHamburger from '~icons/pajamas/hamburger';

	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { HamburgerProps } from '..';
	import { getCtx } from '../ctx';

	let {
		children,
		class: className,
		hamburgerClass = $bindable('')
	}: HamburgerProps & any = $props();

	// Setup Hamburger's class
	let hamburgerCls = $state(cn(hamburgerClass, className));
	$effect(() => {
		hamburgerCls = cn(hamburgerClass, className);
	});

	// Get Drawer Context
	const { show$, toggle_drawer } = getCtx();
</script>

<Flex.Row class={cn('w-full group hamburger pb-3')} data-state={($show$ && 'toggled') || 'un-toggled'}>
	<Separator />
	<Flex.Col
		class={cn(
			`
            hamburger-container
            animate-all duration-500
            size-10 shrink-0 
            items-center justify-center mr-[10px]		
            bg-white/40 hover:bg-white/60 text-primary-500
            cursor-pointer rounded-lg`,
			$show$ ? 'mr-8' : ''
		)}
		onclick={() => toggle_drawer()}
	>
		<svg
			class="size-6 shrink-0"
			viewBox="0 0 24 24"
			fill="currentColor"
			xmlns="http://www.w3.org/2000/svg"
		>
			<rect class="bar-1" x="3" y="5" width="18" height="2" rx="1" fill="currentColor" />
			<rect class="bar-2" x="3" y="11" width="18" height="2" rx="1" fill="currentColor" />
			<rect class="bar-3" x="3" y="17" width="18" height="2" rx="1" fill="currentColor" />
		</svg>
	</Flex.Col>
</Flex.Row>

<!--@component
    Generated by SvelteForge🔥
-->
