<script lang="ts">
	// --- Components ---
	import { Flex, Separator, Drawer } from '@ui';	

	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { MenuProps } from '..';
	import { getCtx } from '../ctx';
	import { fade } from 'svelte/transition';
	import { directives } from '@root/lib/internal/directives';

	let {
		children,
		class: className,
		menuClass = $bindable(
			`animate duration-500
			shrink-0 overflow-hidden 
			flex flex-col 
			w-[300px] h-full 
			bg-primary-500
			pt-[10px]
			border-solid border-0 border-r border-def`
		),

		classBackdrop,
		...rest
	}: MenuProps = $props();

	// Setup Menu's class
	let menuCls = $state(cn(menuClass, className));
	$effect(() => {
		menuCls = cn(menuClass, className);
	});

	// Get Drawer Context
	const { show$, close_drawer, toggle_drawer } = getCtx();
</script>

<!-- Actual Menu -->
<div use:directives class={cn(menuClass, !$show$ && 'w-[60px]' || "pt-6")} onoutclick={() => close_drawer()}>

	<!-- Hamborgor Button -->
	<Drawer.Hamburger/>

	<!-- Children-->
	<Flex.Col class={cn('animate shrink-0 w-15 box-border pl-[10px]', $show$ && 'px-8 w-full')}>
		{@render children?.()}
	</Flex.Col>

	<Separator />
</div>
<!--@component
    Generated by SvelteForge🔥
-->
