<script lang="ts">
	// --- Components ---
	import { Flex, Separator, Span } from '@ui';
	import IconArrow from '~icons/weui/arrow-filled';
	import IconHamburger from '~icons/pajamas/hamburger';

	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { MenuProps } from '..';
	import { getCtx } from '../ctx';
	import { onMount } from 'svelte';
	import { fade } from 'svelte/transition';
	import { cubicInOut } from 'svelte/easing';
	import { directives } from '@root/lib/internal/directives';

	let {
		children,
		class: className,
		menuClass = $bindable(
			'animate shrink-0 overflow-hidden flex flex-col w-[300px] h-full bg-black/20 border-solid border-0 border-r border-def bg-primary-500'
		),

		classBackdrop,
		...rest
	}: MenuProps = $props();

	// Setup Menu's class
	let menuCls = $state(cn(menuClass, className));
	$effect(() => {
		menuCls = cn(menuClass, className);
	});

	// Get Drawer Context
	const { show$ } = getCtx();

	function slide(node: HTMLElement, params: { duration?: number } = {}) {
		const existingTransform = getComputedStyle(node).transform.replace('none', '');

		return {
			duration: params.duration || 300,
			easing: cubicInOut,
			css: (t: number) => `transform: ${existingTransform} translateX(${(1 - t) * -300}px;`
		};
	}

	function closeDrawer() {
		show$.set(false);
	}

	function openDrawer() {
		show$.set(true);
	}

	function toggleDrawer() {
		show$.update((current_show) => {
			return !current_show;
		});
	}
</script>

<!-- Actual Menu -->
<div use:directives class={cn(menuClass, !$show$ && 'w-[60px]')} onoutclick={() => closeDrawer()}>
	<Flex.Col class={cn('size-15 w-full justify-center box-border')}>
		{#if $show$}
			<div transition:fade={{ duration: 150 }}>
				<span class="text-2xl w-full whitespace-nowrap">This is a drawer</span>
			</div>
		{/if}
	</Flex.Col>

	<!-- Hamborgor icon -->
	<Flex.Col class="size-15 bg-red-200 rounded-md">
		<IconHamburger class="size-4 shrink-0"/>
	</Flex.Col>

	<!-- Children-->
	<Flex.Col class={cn('animate shrink-0 w-15 box-border pl-[10px]', $show$ && 'px-8 w-full')}>
		{@render children?.()}
	</Flex.Col>

	<Separator />

	<!-- Minimize Section -->
	<Flex.Row
		class="h-15 w-full p-4 box-border items-center gap-5 text-faded border-solid border-0 border-t border-def select-none"
		onclick={() => toggleDrawer()}
	>
		<IconArrow class={cn('animate size-6 shrink-0 rotate-180', !$show$ && 'rotate-0')} />

		{#if $show$}
			<span class="text-faded" transition:fade>Minimize</span>
		{/if}
	</Flex.Row>
</div>
<!--@component
    Generated by SvelteForge🔥
-->
