<script lang="ts">
	// --- Components ---
	import { Flex } from '@ui';

	// --- Logic ---
	import { base } from "$app/paths"
	import { cn } from '@lib/utils';
	import type { ItemProps } from '..';
	import { getCtx } from '../ctx';
	import { fade } from 'svelte/transition';

	let {
		// Children >)]|
		children,

		// Component Props
		href = undefined,

		// Classes
		class: className,
		itemClass = $bindable(
			'animate box-border px-2 box-border py-2 gap-3 items-center w-10 hover:bg-black/20 select-none rounded-md cursor-pointer text-white dark:text-white'
		),

		// Component Slots
		slot_text,

		...rest
	}: ItemProps = $props();

	// Setup Item's class
	let itemCls = $state(cn(itemClass, className));
	$effect(() => {
		itemCls = cn(itemClass, className);
	});

	href = base + href

	// Get Drawer Context
	const { show$ } = getCtx();
</script>

<svelte:element this={href ? 'a' : 'div'} {href}>
	<Flex.Row class={cn(itemCls, $show$ && 'px-6 w-full')} {...rest}>
		{@render children?.()}
		{#if $show$}
			<div transition:fade>
				{@render slot_text?.()}
			</div>
		{/if}
	</Flex.Row>
</svelte:element>
<!--@component
    Generated by SvelteForge🔥
-->
