<script lang="ts">
	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { Props } from '..';

	let {
		children,
		class: className,
		drawerClass = $bindable('fixed top-0 left-0 size-full bg-red-200'),
		active = $bindable(false)
	}: Props = $props();

	// Setup Drawer's class
	let drawerCls = $state(cn(drawerClass, className));
	$effect(() => {
		drawerCls = cn(drawerClass, className );
	});
</script>

{#if active}
	<div class={drawerCls}>
		{@render children?.()}
	</div>
{/if}
<!--@component
    Generated by SvelteForge🔥
-->
