<script lang="ts">
	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { AnchorProps } from '..';
	import { getCtx } from '../ctx';

	let {
		children,
		class: className,
		anchorClass = $bindable('bg-amber-200'),
		...rest
	}: AnchorProps = $props();

	// Setup Anchor's class
	let anchorCls = $state(cn(anchorClass, className));
	$effect(() => {
		anchorCls = cn(anchorClass, className);
	});

	// Get Drawer Context
	const { show$ } = getCtx();

	/**
	 * Flips the context show$
	 */
	function flipDrawerShow() {
		// Updates the state by flipping it
		show$.update((current_show) => {
			return !current_show;
		});
	}
</script>

<button class={anchorCls} {...rest} onclick={() => flipDrawerShow()}>
	{@render children?.()}
</button>

<!--@component
    Generated by SvelteForge🔥
-->
