<script lang="ts">
	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { ViewProps } from '..';
	import { getCtx, setViewCtx } from '../ctx';
	import { onMount } from 'svelte';
	import { fade } from 'svelte/transition';
	import { cubicIn, cubicInOut, cubicOut } from 'svelte/easing';
	import { clamp, getRelativePercentage } from '@root/lib/internal';

	const {
		transition_progress$,
		in_transition_progress$,
		out_transition_progress$,
		default_in_start$,
		default_in_end$,
		default_out_start$,
		default_out_end$,
		is_shown$
	} = setViewCtx();

	let {
		children,
		backdrop,
		class: className,
		viewClass = $bindable(`
            relative z-0
            size-full       
			transition-all   
			animate ease-out duration-300
        `),

		// Container <inner> Default
		containerClass = $bindable(`
            relative z-1
            size-full
            flex flex-col
        `),

		// Container <inner> Custom
		classContainer = $bindable(`
        
        `),
		in_transition,
		out_transition,
		transition,
		in_start = $default_in_start$,
		in_end = $default_in_end$,
		out_start = $default_out_start$,
		out_end = $default_out_end$,
		full_transition_progress = $bindable(0),
		in_transition_progress = $bindable(0),
		out_transition_progress = $bindable(0)
	}: ViewProps = $props();

	if (transition) {
		in_transition = transition;
		out_transition = transition;
	}

	// Setup View's class
	let viewCls = $state(cn(viewClass, className));
	let containerCls = $state(cn(containerClass, classContainer));
	$effect(() => {
		viewCls = cn(viewClass, className);
		containerClass = cn(containerClass, classContainer);
	});

	// Get Root & Set View Context
	const { view_count$, scroll_delta$, root_height$ } = getCtx();

	// Current View Order
	let order = $state(0);
	let start_position = $derived(order * $root_height$);
	let is_shown = $derived(
		$scroll_delta$ >= start_position && $scroll_delta$ <= start_position + $root_height$
	);

	$effect(() => {
		is_shown$.set(is_shown)
	})

	$effect(() => {
		full_transition_progress = !is_shown
			? 0
			: Math.abs($root_height$ * order - $scroll_delta$) / $root_height$;
	});

	$effect(() => {
		in_transition_progress = !is_shown
			? 0
			: getRelativePercentage(full_transition_progress, in_start, in_end);
	});

	$effect(() => {
		out_transition_progress = !is_shown
			? 0
			: getRelativePercentage(full_transition_progress, out_start, out_end);
	});

	let elem_transition = $state('');

	$effect(() => {
		transition_progress$.set(full_transition_progress);
		if (in_transition_progress >= 0 && in_transition_progress < 1) {
			// Do In Transition
			if (!in_transition) return;
			in_transition_progress$.set(in_transition_progress);
			elem_transition = in_transition(in_transition_progress);
		} else {
			// Do out Transition
			if (!out_transition) return;
			out_transition_progress$.set(Math.abs(out_transition_progress - 1));
			elem_transition = out_transition(Math.abs(out_transition_progress - 1));
		}
	});

	// svelte-ignore state_referenced_locally

	onMount(() => {

		order = $view_count$;
		view_count$.update((c_view_count) => {
			return c_view_count + 1;
		});

		// Set Defaults
		console.log(in_start, in_end, out_start, out_end)
		default_in_start$.set(in_start);
		default_in_end$.set(in_end);
		default_out_start$.set(out_start);
		default_out_end$.set(out_end)

		

		return () => {
			// Subtract from root view count
			view_count$.update((c_view_count) => {
				return c_view_count - 1;
			});
		};
	});
</script>

<div class={cn(viewCls, !is_shown && "hidden")} style={elem_transition}>
	{@render backdrop?.()}

	<div class={containerCls}>
		{@render children?.()}
	</div>
</div>
<!--@component
    Generated by SvelteForge🔥
-->
