<script lang="ts">
	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { BooleanProps } from '..';
	import { getViewCtx } from '../ctx';
	import { getRelativePercentage } from '@root/lib/internal';

	const {
		transition_progress$,
		in_transition_progress$,
		out_transition_progress$,
		default_in_start$,
		default_in_end$,
		default_out_start$,
		default_out_end$,
		is_shown$
	} = getViewCtx();

	let {
		children,
		class: className,
		booleanClass = $bindable(''),
		in_start = $default_in_start$,
		in_end = $default_in_end$,
		out_start = $default_out_start$,
		out_end = $default_out_end$
	}: BooleanProps = $props();

	// Setup Boolean's class
	let booleanCls = $state(cn(booleanClass, className));
	$effect(() => {
		booleanCls = cn(booleanClass, className);
	});

	const in_progress = $derived(getRelativePercentage($transition_progress$, in_start, in_end));
	const out_progress = $derived(getRelativePercentage($transition_progress$, out_start, out_end));

	$effect(() => {
		console.log(out_progress);
	});
</script>

<span>{in_progress} | {out_progress}</span>
{#if out_progress == 0}
	<!-- Should Show -->
	<div>
		{@render children?.()}
	</div>
{/if}

<!--@component
    Generated by SvelteForge🔥
-->
