<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { ViewProps } from ".."
	import { getCtx, setViewCtx } from '../ctx';
    
    let {
        children,
        class: className,
        viewClass = $bindable('')
    }: ViewProps = $props();


    // Setup View's class
    let viewCls = $state(cn(viewClass, className));
    $effect(() => {
        viewCls = cn(viewClass, className)
    })

    // Get Root & Set View Context
    const { state$ } = getCtx();
    const { otherstate$ } = setViewCtx({});


</script>

<div class={ viewCls }>
    {@render children?.()}
</div>

<!--@component
    Generated by SvelteForge🔥
-->

