<script lang="ts">
	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { BackdropProps } from '..';
	import { getCtx, getViewCtx } from '../ctx';
	import { onMount } from 'svelte';

	let {
		children,
		class: className,
		backdropClass = $bindable(`
			absolute top-0 left-0 z-0
			size-full
			[&>*]:select-none
			
		`),
		el = $bindable(undefined)
	}: BackdropProps = $props();

	// Setup Backdrop's class
	let backdropCls = $state(cn(backdropClass, className));
	$effect(() => {
		backdropCls = cn(backdropClass, className);
	});

	// Get Root & View Contexts
	const { state$, combined_height$ } = getCtx();	

	
</script>

<div class={backdropCls} bind:this={el}>
	{@render children?.()}
</div>

<!--@component
    Generated by SvelteForge🔥
-->
