<script lang="ts">
	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { BackdropProps } from '..';
	import { getCtx, getViewCtx } from '../ctx';

	let { children, class: className, backdropClass = $bindable('') }: BackdropProps = $props();

	// Setup Backdrop's class
	let backdropCls = $state(cn(backdropClass, className));
	$effect(() => {
		backdropCls = cn(backdropClass, className);
	});

	// Get Root & View Contexts
	const { state$ } = getCtx();
	const { otherstate$ } = getViewCtx();
</script>

<div class={backdropCls}>
	{@render children?.()}
</div>

<!--@component
    Generated by SvelteForge🔥
-->
