<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { ViewProps } from ".."
    
    let {
        children,
        class: className,
        viewClass = $bindable('')
    }: ViewProps = $props();


    // Setup View's class
    let viewCls = $state(cn(viewClass, className));
    $effect(() => {
        viewCls = cn(viewClass, className)
    })

</script>

<div class={ viewCls }>
    {@render children?.()}
</div>

<!--@component
    Generated by SvelteForge🔥
-->

