<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { BackdropProps } from ".."
    
    let {
        children,
        class: className,
        backdropClass = $bindable('')
    }: BackdropProps = $props();


    // Setup Backdrop's class
    let backdropCls = $state(cn(backdropClass, className));
    $effect(() => {
        backdropCls = cn(backdropClass, className)
    })

</script>

<div class={ backdropCls }>
    {@render children?.()}
</div>

<!--@component
    Generated by SvelteForge🔥
-->

