<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { Props } from ".."
	import { setCtx } from '../ctx';
    
    let {
        children,
        class: className,
        fscrollableClass = $bindable('')
    }: Props = $props();


    // Setup Fscrollable's class
    let fscrollableCls = $state(cn(fscrollableClass, className));
    $effect(() => {
        fscrollableCls = cn(fscrollableClass, className)
    })

    // Set Root Context
    setCtx({});

</script>

<div class={ fscrollableCls }>
    {@render children?.()}
</div>

<!--@component
    Generated by SvelteForge🔥
-->

