<script lang="ts">
	// --- Components ---
	import { Flex } from '@ui';

	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { Props } from '..';

	let {
		class: className,
		checkboxClass = $bindable(`
            w-15 h-6.5
            rounded-sm
            animate ease-out
            relative
            cursor-pointer
            justify-center
            pl-[6%]
			box-border
        `),
		containerClass = $bindable(`
            justify-start items-start size-fit
        `),
		classContainer = $bindable(``),
		value = $bindable(false),
		inputValue = $bindable(''),

		...rest // Rest
	}: Props = $props();

	// Setup Checkbox's class
	let checkboxCls = $state(cn(checkboxClass, className));
	$effect(() => {
		checkboxCls = cn(checkboxClass, className);
	});

	function onclick() {
		value = !value; // Toggle Value
		inputValue = value ? 'yes' : 'no'; // Reflect input value
	}
</script>

<input value={inputValue} class="hidden" {...rest}/>

<Flex.Row class={cn(containerClass, classContainer)}>
	<Flex.Col class={cn(checkboxCls, `bg-red pl-[7%]`, value && 'bg-green pl-[65%]')} {onclick}>
		<Flex.Root class={cn('size-4 rounded-sm bg-white ', value && '')} />
	</Flex.Col>
</Flex.Row>

<!--@component
    Generated by SvelteForge🔥
-->
