<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { Props } from ".."
    
    let {
        children,
        class: className,
        checkboxClass = $bindable('')
    }: Props = $props();


    // Setup Checkbox's class
    let checkboxCls = $state(cn(checkboxClass, className));
    $effect(() => {
        checkboxCls = cn(checkboxClass, className)
    })

</script>

<div class={ checkboxCls }>
    {@render children?.()}
</div>

<!--@component
    Generated by SvelteForge🔥
-->

