<script lang="ts">
	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { Props } from '..';
	import { writable, type Writable } from 'svelte/store';
	import { onMount, setContext } from 'svelte';

	let {
		children,
		class: className,
		formClass = $bindable('flex flex-col'),
		onsubmit = $bindable(undefined),
		ref = $bindable(undefined)
	}: Props & any = $props();

	const ref$: Writable<HTMLFormElement | undefined> = writable(undefined);

	// Setup Form's class
	let formCls = $state(cn(formClass, className));
	$effect(() => {
		formCls = cn(formClass, className);
	});

	/**
	 * Determines whether or not custom functionality has been implemented for the form.
	 * @param event
	 */
	function handleSubmit(event: SubmitEvent) {
		if (onsubmit) {
			event.preventDefault();
			onsubmit(event);
		}
	}

	onMount(() => {
		const interval = setInterval(() => {
			if (!ref) return;
			ref$.set(ref);

			setTimeout(() => {
				const changeEvt = new Event('change', { bubbles: true });
				ref.dispatchEvent(changeEvt);
			}, 100);

			clearInterval(interval);
		});
	});

	setContext('form-data', { ref$: ref$ });
</script>

<form class={formCls} onsubmit={handleSubmit} bind:this={ref}>
	{@render children?.()}
</form>

<!--@component
    Generated by SvelteForge🔥
-->
