<script lang="ts">
	// --- Components ---
	import { Flex, Span } from '@ui';

	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { InputProps } from '..';

	let {
		children,
		class: className,
		label,

		// Default Classes
		containerClass = $bindable(''),
		inputClass = $bindable('box-border w-full rounded-xs p-2 bg-black/10 dark:bg-white'),
		labelClass = $bindable('text-[1rem] text-subtle'),
		source_value = $bindable(undefined),

		// User Defined Classes
		classContainer,
		classLabel,

		// Slots
		slot_inside,

		...rest
	}: InputProps = $props();

	// Setup Input's class
	let containerCls = $state(cn(containerClass, classContainer));
	let labelCls = $state(cn(labelClass, classLabel));
	let inputCls = $state(cn(inputClass, className));

	$effect(() => {
        // Make all classes reactive so if we change it in runtime, it reflects that change
        containerCls = cn(containerClass, classContainer)
		labelCls = cn(labelClass, classLabel);
		inputCls = cn(inputClass, className);
	});
</script>

<!-- Container for both the label and the input component-->
<Flex.Col class={ containerCls }>

	{@render children?.()}
	
	<!-- only render a label if one is specified -->
	{#if label}
		<Span class={ labelCls }>{label}</Span> <!-- By default, this already has a mode:reactive color change-->
	{/if}

	<!-- Render input element -->
	<input class={ inputCls } {...rest}/>
</Flex.Col>

<!--@component
    Generated by SvelteForge🔥
-->
