<script lang="ts">
	// --- Components ---
	import { Flex } from '@ui';

	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { CheckboxProps } from '..';
	import Span from '../../span/components/span.svelte';

	let {
		class: className,

		label,
		value = $bindable(false),
		inputValue,

		// Default Classes
		containerClass = $bindable('gap-5 items-center w-fit'),
		inputClass = $bindable('hidden'),
		checkboxClass = $bindable('relative size-5 px-[5px] rounded-full cursor-pointer'),

		// User Defined Classes
		classContainer = $bindable(''),
		classInput = $bindable(''),
		classCheckbox = $bindable(''),

		// Rest of the props to pass to the input element
		...rest
	}: CheckboxProps = $props();

	// Setup Checkbox's class
	let containerCls = $state(cn(containerClass, classContainer));
	let inputCls = $state(cn(inputClass, classInput));
	let checkboxCls = $state(cn(checkboxClass, className));
	$effect(() => {
		containerCls = cn(containerClass, classContainer);
		inputCls = cn(inputClass, classInput);
		checkboxCls = cn(checkboxClass, className);
	});

	// Flip the value of this component
	function flip_value() {
		value = !value;
        if (value) {
            inputValue = "yes"
        } else {
            inputValue = "no"
        }

        console.log(value, inputValue)
	}
</script>

<input value={inputValue} class={inputCls} {...rest} />
<!-- Dummy Component for form compatibility -->

<Flex.Row class={containerCls}>
	{#if label}
		<Span>{label}</Span>
	{/if}
	<Flex.Row
		class={cn(checkboxCls, 'bg-red-300 ', value && 'bg-green-200')}
		onclick={() => flip_value()}
	/>
</Flex.Row>

<!--@component
    Generated by SvelteForge🔥
-->
