<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { Props } from ".."
    
    let {
        children,
        class: className,
        formClass = $bindable('flex flex-col'),
        onsubmit = $bindable(undefined)
    }: Props & any = $props();


    // Setup Form's class
    let formCls = $state(cn(formClass, className));
    $effect(() => {
        formCls = cn(formClass, className)
    })

    /**
     * Determines whether or not custom functionality has been implemented for the form.
     * @param event
     */
    function handleSubmit(event: SubmitEvent) {
        if (onsubmit) {
            event.preventDefault()
            onsubmit(event);
        }
    }    
</script>

<form class={ formCls } onsubmit={handleSubmit}>
    {@render children?.()}
</form>

<!--@component
    Generated by SvelteForge🔥
-->

