<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { Props } from ".."
    
    let {
        children,
        class: className,
        formClass = $bindable('flex flex-col')
    }: Props & any = $props();


    // Setup Form's class
    let formCls = $state(cn(formClass, className));
    $effect(() => {
        formCls = cn(formClass, className)
    })

</script>

<form class={ formCls }>
    {@render children?.()}
</form>

<!--@component
    Generated by SvelteForge🔥
-->

