<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { Props } from ".."


    let {
        children,
        class: className,
        priceHandlerClass = $bindable('text-sm text-[#319F43]'),
        price = 0
    }: Props = $props();


    // Setup PriceHandler's class
    let priceHandlerCls = $state(cn(priceHandlerClass, className));
    $effect(() => {
        priceHandlerCls = cn(priceHandlerClass, className)
    })

</script>




<span class={ priceHandlerCls }>+${price}</span>


<!--@component
    Generated by SvelteForge🔥
-->

